type SanboxUser {
	id: Int!
	name: String!
}

type Sandbox {
	message: String!
	sum(a: Int!, b: Int!): Int!
	list: [Int!]
	user(id: Int!): SanboxUser
	asyncUser(id: Int!): SanboxUser
	errorMaybe: String
	errorDefinitely: String
	exceptionMaybe: String
	exceptionDefinitely: String!
	exceptionPromise: String!
}

type Query {
	sandbox: Sandbox
}
