type User {
	id: Int!
	name: String!
}

type Sandbox {
	message: String!
	sum(a: Int!, b: Int!): Int!
	list: [Int!]
	user(id: Int!): User
	asyncUser(id: Int!): User
	errorMaybe: String
	errorDefinitely: String!
	exceptionMaybe: String
	exceptionDefinitely: String!
	exceptionPromise: String!
}
